services:
  # Order Service
  order-service:
    build: ../../services/order-service
    container_name: order-service
    ports:
      - "8001:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/microservices_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - postgres
      - redis
    networks:
      - kafka-network
    volumes:
      - ../../services/order-service:/app
      - ../../shared:/app/shared
