services:
  # Inventory Service
  inventory-service:
    build: ../../services/inventory-service
    container_name: inventory-service
    ports:
      - "8003:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/microservices_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - kafka
      - postgres
      - redis
    networks:
      - kafka-network
    volumes:
      - ../../services/inventory-service:/app
      - ../../shared:/app/shared
